apiVersion: v1
data:
  OPENAI_API_KEY: c2stcHJvai1QU3lhMmREcHdoakppdXZnRGpOUmdlbldDNXNBdi0tb1FNaUQ3Qm5YaERNWFJmd3JBRVlwZjhmbVgzSGZZYjZNdnFmd1g4NF96c1QzQmxia0ZKZ190OGhFOVB4N3gzdnpFczBjc2FNVk1Wd1g0R2xGVXp1TS1veDM1MFN6UzNOUjhzdk9xSXF3U1ZnTTlnS2NEN2l5LWVTQzRxNEE=
  POSTGRES_PASSWORD: cXdlcnR5
  POSTGRES_USERNAME: cG9zdGdyZXM=
kind: Secret
metadata:
  name: django-secret
  namespace: aigen
